stages:
  - build

create-latest-image:
  stage: build
  image: docker:latest
  services:
   - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

create-linux-binary:
  stage: build
  image: golang:latest
  script:
    - ln -s $(pwd) $GOPATH/src/$CI_PROJECT_NAME
    - CGO_ENABLED=0 go install $CI_PROJECT_NAME
    - mv $GOPATH/bin/$CI_PROJECT_NAME ./deployment
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - deployment/
  only:
    - master
