version: '2'
services:
  deployer:
    image: <registry>/<charts-repo>
    restart: unless-stopped
    environment:
      - DEPLOYER_WEBHOOK_PORT=3000
      - DEPLOYER_WEBHOOK_K8S_ACCESS_KEY=<key>
      - DEPLOYER_WEBHOOK_K8S_ACCESS_TOKEN=<token>
    volumes:
      - ./deployer:/root/.deployer/
    networks:
      - server
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=deployer-k1'
      - 'traefik.frontend.rule=Host:deployer.example.com'
      - 'traefik.docker.network=traefik_webgateway'
      - 'com.centurylinklabs.watchtower.enable=true'
  
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    labels:
      - 'traefik.enable=false'

networks:
  server:
    external:
      name: traefik_webgateway
