version: '2'
services:
  deployer:
    image: <registry>/<charts-repo>
    restart: unless-stopped
    environment:
      - DEPLOYER_WEBHOOK_PORT=${DEPLOYER_WEBHOOK_PORT}
      - DEPLOYER_WEBHOOK_K8S_ACCESS_KEY=${DEPLOYER_WEBHOOK_K8S_ACCESS_KEY}
      - DEPLOYER_WEBHOOK_K8S_ACCESS_TOKEN=${DEPLOYER_WEBHOOK_K8S_ACCESS_TOKEN}
    volumes:
      - ./deployer:/root/.deployer/
    networks:
      - traefik
      - default
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.${DEPLOYER_BACKEND}.rule=Host(`${DEPLOYER_BACKEND}.${DEPLOYER_ROOT_DOMAIN}`)"
      - "traefik.http.routers.${DEPLOYER_BACKEND}.service=${DEPLOYER_BACKEND}"
      - "traefik.http.services.${DEPLOYER_BACKEND}.loadbalancer.server.port=${DEPLOYER_WEBHOOK_PORT}"
      - 'traefik.docker.network=${TRAEFIK_NETWORK}'
  
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    labels:
      - 'traefik.enable=false'

networks:
  traefik:
    name: ${TRAEFIK_NETWORK}
    external: true
