version: '2'
services:
  deployer:
    image: registry.gitlab.com/nithinbose/deployer:latest-docker-compose
    restart: unless-stopped
    environment:
      - DEPLOYER_WEBHOOK_PORT=${DEPLOYER_WEBHOOK_PORT}
      - DEPLOYER_WEBHOOK_DOCKER_ACCESS_KEY=${DEPLOYER_WEBHOOK_DOCKER_ACCESS_KEY}
      - DEPLOYER_WEBHOOK_DOCKER_ACCESS_TOKEN=${DEPLOYER_WEBHOOK_DOCKER_ACCESS_TOKEN}
    volumes:
      - ~/.docker:/root/.docker
      - ${DEPLOYER_DOCKER_STACKS_PATH}:/root/docker-stacks
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
      - default
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.${DEPLOYER_BACKEND}.rule=Host(`${DEPLOYER_BACKEND}.${DEPLOYER_ROOT_DOMAIN}`)"
      - "traefik.http.routers.${DEPLOYER_BACKEND}.service=${DEPLOYER_BACKEND}"
      - "traefik.http.services.${DEPLOYER_BACKEND}.loadbalancer.server.port=${DEPLOYER_WEBHOOK_PORT}"
      - 'traefik.docker.network=${TRAEFIK_NETWORK}'

networks:
  traefik:
    name: ${TRAEFIK_NETWORK}
    external: true