version: '2'
services:
  deployer:
    image: registry.gitlab.com/nithinbose/deployer:latest-docker-compose
    restart: unless-stopped
    environment:
      - DEPLOYER_WEBHOOK_PORT=3000
      - DEPLOYER_WEBHOOK_DOCKER_ACCESS_KEY=<key>
      - DEPLOYER_WEBHOOK_DOCKER_ACCESS_TOKEN=<token>
    volumes:
      - ~/.docker:/root/.docker
      - ./docker-stacks:/root/docker-stacks
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - server
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=deployer-k1'
      - 'traefik.frontend.rule=Host:deployer.example.com'
      - 'traefik.docker.network=traefik_webgateway'
      - 'com.centurylinklabs.watchtower.enable=true'

networks:
  server:
    external:
      name: traefik_webgateway
