version: '2'
services:
  deployer:
    image: registry.gitlab.com/nithinbose/deployer:latest-docker-compose
    restart: unless-stopped
    environment:
      - DEPLOYER_WEBHOOK_PORT=3000
      - DEPLOYER_WEBHOOK_DOCKER_ACCESS_KEY=${DEPLOYER_WEBHOOK_DOCKER_ACCESS_KEY}
      - DEPLOYER_WEBHOOK_DOCKER_ACCESS_TOKEN=${DEPLOYER_WEBHOOK_DOCKER_ACCESS_TOKEN}
    volumes:
      - ~/.docker:/root/.docker
      - ${DEPLOYER_DOCKER_STACKS_PATH}:/root/docker-stacks
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=${DEPLOYER_BACKEND}'
      - 'traefik.frontend.rule=Host:${DEPLOYER_BACKEND}.${DEPLOYER_ROOT_DOMAIN}'
      - 'traefik.docker.network=traefik_default'

networks:
  traefik:
    name: traefik_default
    external: true