version: '2'
services:
  deployer:
    image: <registry>/<charts-repo>
    restart: unless-stopped
    environment:
      - DEPLOYER_WEBHOOK_PORT=3000
      - DEPLOYER_WEBHOOK_K8S_ACCESS_KEY=${DEPLOYER_WEBHOOK_K8S_ACCESS_KEY}
      - DEPLOYER_WEBHOOK_K8S_ACCESS_TOKEN=${DEPLOYER_WEBHOOK_K8S_ACCESS_TOKEN}
    volumes:
      - ./deployer:/root/.deployer/
    networks:
      - traefik
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=${DEPLOYER_BACKEND}'
      - 'traefik.frontend.rule=Host:${DEPLOYER_BACKEND}.${DEPLOYER_ROOT_DOMAIN}'
      - 'traefik.docker.network=traefik_default'
      - 'com.centurylinklabs.watchtower.enable=true'
  
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    labels:
      - 'traefik.enable=false'

networks:
  traefik:
    name: traefik_default
    external: true
